from typing import TypedDict, Optional, Annotated
from langgraph.graph.message import add_messages


class WorkflowState(TypedDict):
    # Slack context
    slack_channel: str
    slack_thread_ts: str
    triggered_by: str

    # JIRA tickets in Review column
    jira_tickets: list[dict]

    # Results per ticket (keyed by ticket ID)
    test_cases: dict         # ticket_id -> markdown test cases (generated by designer)
    test_results: dict       # ticket_id -> {"raw": str, "action_log": dict|None, "_exit_code": int}
    action_logs: dict        # ticket_id -> parsed action log JSON (hand-off to automator)
    automation_scripts: dict # ticket_id -> generated .spec.ts paths
    test_summary: dict       # ticket_id -> human-readable summary

    # GitHub PRs created by the automator (keyed by ticket ID)
    github_prs: dict  # ticket_id -> {branch, pr_url, pr_number}

    # Final report posted to Slack
    report: str

    # Flow control
    error: Optional[str]
